// 自动生成：node scripts/generate-quotes.mjs（数据源：ShowArchive/戏剧台词列表.md）

export interface Quote {
  lang: string
  original: string
  translation: string
  play: string
  song: string
}

export const QUOTES: Quote[] = [
  {"lang":"中文","original":"愛恨從來是否相生，是否相抵，竟像謎。","translation":"","play":"《大狀王》","song":"撒一場白米"},
  {"lang":"中文","original":"一個念頭，一番宇宙，前路再可以走。","translation":"","play":"《大狀王》","song":"一念一宇宙"},
  {"lang":"中文","original":"放心，放膽，無懼雨霧彌漫\n見山，過山，行動勝於嗟嘆","translation":"","play":"《大狀王》","song":"道德經"},
  {"lang":"中文","original":"未来或许，当我，用气力舞起狮头\n如像我跨越宇宙。","translation":"","play":"《雄狮少年》","song":"《雄狮》"},
  {"lang":"中文","original":"我不能看见黑暗欺压星光，因为我心也要一直点亮。","translation":"","play":"《赵氏孤儿》","song":"《绝不可以》"},
  {"lang":"中文","original":"文字有千百力量，为苍生医创伤。","translation":"","play":"《小说》粤语版","song":"（歌名未详）"},
  {"lang":"中文","original":"国是已不可问，我辈且打麻将。","translation":"","play":"《蒋公的面子》","song":""},
  {"lang":"中文","original":"我宁愿失恋，也不要三缺一。","translation":"","play":"《蒋公的面子》","song":""},
  {"lang":"中文","original":"我的面子比天大！","translation":"","play":"《蒋公的面子》","song":""},
  {"lang":"中文","original":"这个日子真是没法过了！","translation":"","play":"《蒋公的面子》","song":""},
  {"lang":"英语","original":"But now, god knows, anything goes.","translation":"但现在，天知道，万事皆可。","play":"《万事皆可》","song":"Anything Goes"},
  {"lang":"英语","original":"You've taken the bravado out of me.","translation":"你让我的心有些小路乱撞。","play":"《傲慢与偏见》","song":"Bravado"},
  {"lang":"英语","original":"Who lives, who dies, who tells your story?","translation":"谁活着，谁死去，谁来讲述你的故事？","play":"《汉密尔顿》","song":"Who Lives, Who Dies, Who Tells Your Story"},
  {"lang":"英语","original":"History has its eyes on you.","translation":"历史正注视着你。","play":"《汉密尔顿》","song":"History Has Its Eyes on You"},
  {"lang":"英语","original":"There can be miracles when you believe.","translation":"当你相信时就会有奇迹。","play":"《埃及王子》","song":"When You Believe"},
  {"lang":"英语","original":"hough hope is frail, it's hard to kill.","translation":"虽然希望脆弱，却难以扼杀。","play":"《埃及王子》","song":"When You Believe"},
  {"lang":"英语","original":"Climb every mountain, ford every stream, follow every rainbow, till you find your dream.","translation":"攀登每一座高山，跋涉每一条溪流，追随每一道彩虹，直到找到你的梦想。","play":"《音乐之声》","song":"Climb Ev'ry Mountain"},
  {"lang":"英语","original":"Measure your life in love.","translation":"用爱丈量你的生命。","play":"《吉屋出租》","song":"Seasons of Love"},
  {"lang":"英语","original":"No day but today.","translation":"没有哪一天，只有今天。","play":"《吉屋出租》","song":"Seasons of Love"},
  {"lang":"英语","original":"Just because you find that life's not fair, it doesn't mean that you just have to grin and bear it.","translation":"就算你发现生活不公，也不意味着你只能咬牙忍受。","play":"《玛蒂尔达》","song":"Naughty"},
  {"lang":"英语","original":"You mustn't let a little thing like 'little' stop you.","translation":"你不能让“渺小”这种小事阻挡你。","play":"《玛蒂尔达》","song":"Naughty"},
  {"lang":"英语","original":"When I grow up, I will be brave enough to fight the creatures that you have to fight.","translation":"等我长大了，我会足够勇敢，去对抗那些你不得不对抗的怪物。","play":"《玛蒂尔达》","song":"When I Grow Up"},
  {"lang":"英语","original":"Somewhere over the rainbow, dreams that you dare to dream really do come true.","translation":"在彩虹之上的某处，你敢做的梦终会成真。","play":"《绿野仙踪》","song":"Over the Rainbow"},
  {"lang":"英语","original":"You are not alone. You will be found.","translation":"你并不孤单，你会被找到。","play":"《致埃文·汉森》","song":"You Will Be Found"},
  {"lang":"英语","original":"To dream the impossible dream, to fight the unbeatable foe.","translation":"去梦想那不可能的梦想，去对抗那不可战胜的敌人。","play":"《我，堂吉诃德》","song":"The Impossible Dream"},
  {"lang":"英语","original":"If only you would listen - I promise one day I'll make you hear.","translation":"只要你愿意倾听——我保证总有一天我会让你听见。","play":"《摇滚学校》","song":"If Only You Would Listen"},
  {"lang":"英语","original":"You're in the band.","translation":"你就是乐队的一员。","play":"《摇滚学校》","song":"You’re in the Band"},
  {"lang":"英语","original":"And if you wanna be the teacher's pet\nBaby, you just better forget it","translation":"","play":"《摇滚学校》","song":"You’re in the Band"},
  {"lang":"英语","original":"We demand to be heard. We demand to be seen. We demand to be known.","translation":"我们要求被倾听，被看见，被知晓。","play":"《Suffs》","song":"The March"},
  {"lang":"英语","original":"Progress is possible, not guaranteed.\n","translation":"进步是可能的，但并非理所当然。","play":"《Suffs》","song":"Keep Marching"},
  {"lang":"英语","original":"Keep marching on.","translation":"继续前进。","play":"《Suffs》","song":"Keep Marching"},
  {"lang":"英语","original":"Feed your fire, to take you higher.","translation":"点燃你的火焰，带你飞得更高。","play":"《长靴皇后》","song":"Raise You Up / Just Be"},
  {"lang":"英语","original":"You can be who you wanna be, just be who you wanna be.","translation":"你可以成为你想成为的人，就做你想做的那个人。","play":"《长靴皇后》","song":"Just Be"},
  {"lang":"英语","original":"Close your eyes and let your spirit start to soar\nAnd you'll live as you've never lived before","translation":"闭上双眼让灵魂翱翔，你将活出从未有过的模样。","play":"《剧院魅影》","song":"The Music of the Night"},
  {"lang":"英语","original":"Let me be your shelter, let me be your light.","translation":"让我做你的庇护，让我做你的光。","play":"《剧院魅影》","song":"All I Ask of You"},
  {"lang":"英语","original":"Daylight, see the dew on the sunflower\nAnd a rose that is fading\nLet your memory live again","translation":"晨光中向日葵上的露珠，和凋零的玫瑰——让你的回忆重获新生。","play":"《猫》","song":"Memory"},
  {"lang":"英语","original":"To conquer death you only have to die.","translation":"要战胜死亡，你只需经历死亡。","play":"《万世巨星》","song":"Poor Jerusalem"},
  {"lang":"英语","original":"I'm gonna live till I die.","translation":"我要尽情活着直到死去。","play":"《芝加哥》","song":"All That Jazz"},
  {"lang":"英语","original":"How can they hear the truth above the roar?","translation":"在喧嚣之上，他们怎么听得见真相？","play":"《芝加哥》","song":"Razzle Dazzle"},
  {"lang":"英语","original":"I was a girl who dreamed of the sky, to fly so high.","translation":"我曾是个仰望天空的女孩，想要飞到那么高。","play":"《来自远方》","song":"Me and the Sky"},
  {"lang":"英语","original":"I'm gonna be so much better, I'm gonna turn it all around.","translation":"我会变得更好，我会扭转一切。","play":"《律政俏佳人》","song":"So Much Better"},
  {"lang":"英语","original":"Gay or European","translation":"","play":"《律政俏佳人》","song":"Gay or European"},
  {"lang":"英语","original":"Even the darkest night will end.","translation":"即使最黑暗的夜晚也终将结束。","play":"《悲惨世界》","song":"Epilogue"},
  {"lang":"法语","original":"Je veux la gloire à mes genoux.","translation":"我要荣耀向我俯首。","play":"《摇滚红与黑》","song":"La gloire à mes genoux"},
  {"lang":"法语","original":"Je dors sur des roses, mais je rêve d'ailleurs\nJe rêve d'un ailleurs que je connais par cœur","translation":"我睡在玫瑰上，但我的梦在别处——那个我早已烂熟于心的别处。","play":"《摇滚莫扎特》","song":"Je dors sur des roses"},
  {"lang":"法语","original":"Penser l'impossible, brûler nos prisons dorées, ouvrir les portes du futur.","translation":"思考不可能之事，烧毁镀金的牢笼，打开未来之门。","play":"《摇滚莫扎特》","song":"Penser l'impossible"},
  {"lang":"法语","original":"Aimer, c'est monter si haut, et toucher les ailes des oiseaux\nAimer, c'est ce qu'il y a de plus beau","translation":"爱，是登峰造极，是轻抚飞鸟的翅膀——爱是最美的存在。","play":"《罗密欧与朱丽叶》","song":"Aimer"},
  {"lang":"法语","original":"Rêver j'en ai l'habitude\nRêver, c'est ma seule attitude","translation":"我早就习惯了做梦，做梦是我唯一的态度。","play":"《莫里哀》","song":"Rêver j'en ai l'habitude"},
  {"lang":"法语","original":"Aujourd'hui tout va bien.","translation":"今日万事顺意。","play":"《莫里哀》","song":"Aujourd'hui tout va bien"},
  {"lang":"法语","original":"T'aimer est une galère qui ne cesse de prendre l'eau.","translation":"爱你如苦海行舟，渗水不止将我淹没。","play":"《莫里哀》","song":"T'aimer est une galère"},
  {"lang":"法语","original":"Si je veux tout donner tout donner.","translation":"若我想要，一切的一切，都能给我。","play":"《莫里哀》","song":"Moi je veux"},
  {"lang":"法语","original":"Laisse mon peuple s'en aller, dis-lui de briser ses chaînes.","translation":"让我的人民走吧，告诉他去打破枷锁。","play":"《十诫》","song":"Laisse mon peuple s'en aller"},
  {"lang":"法语","original":"Tant qu'on rêve encore, tant qu'on aime encore.","translation":"只要我们还梦想，只要我们还爱着。","play":"《太阳王》","song":"Tant qu'on rêve encore"},
  {"lang":"法语","original":"Ça ira, tout le monde chantera.","translation":"一切都会好的，所有人都会歌唱。","play":"《1789：巴士底狱的恋人》","song":"Ça ira"},
  {"lang":"德语","original":"Ich gehör nur mir.","translation":"我只属于我自己。","play":"《伊丽莎白》","song":"Ich gehör nur mir"},
  {"lang":"德语","original":"Ich wehr' mich, bevor ich mich verlier'.","translation":"在失去自己之前，我要反抗。","play":"《伊丽莎白》","song":"Ich gehör nur mir"},
  {"lang":"德语","original":"Wie wird man seinen Schatten los? Wie sagt man seinem Schicksal Nein?","translation":"人如何摆脱自己的影子？如何对命运说不？","play":"《莫扎特！》","song":"Wie wird man seinen Schatten los?"},
  {"lang":"德语","original":"Ich bin, ich bin Musik\nIch bin der Klang, der durch die Nacht zieht","translation":"我是，我就是音乐，我是穿越黑夜的声音。","play":"《莫扎特！》","song":"Ich bin, ich bin Musik"},
  {"lang":"德语","original":"Die Wunder kommen wieder jedenfalls für mich.","translation":"奇迹无论如何会为我再次降临。","play":"《莫扎特！》","song":"Ich bin, ich bin Musik"},
  {"lang":"德语","original":"Man muss sich entscheiden，welche Maske man trägt, welchen Weg man geht.","translation":"人必须做出选择——戴哪副面具，走哪条路。","play":"《莫扎特！》","song":"Der Einfache Weg"},
  {"lang":"德语","original":"Sein heißt Werden, Leben heißt Lernen.","translation":"想生存，须成长，欲生活，须学习。","play":"《莫扎特！》","song":"Gold von den Sternen"},
  {"lang":"德语","original":"Wir folgen unsrem Stern und werden neu geboren aus Asche und aus Staub.","translation":"我们追随我们的星星，从灰烬与尘土中获得重生。","play":"《路德维希二世》","song":"（歌名未详）"},
  {"lang":"德语","original":"Heut' Nacht verzauber' ich die Welt.","translation":"今晚我让世界着迷。","play":"《蝴蝶梦》","song":"Heut' Nacht verzauber' ich die Welt"},
  {"lang":"德语","original":"Wie man Zeit in eine Flasche füllt.","translation":"如何把时间装进瓶子里。","play":"《蝴蝶梦》","song":"Zeit in einer Flasche"},
  {"lang":"俄语","original":"Пришла наконец моя весна\nДуша моя оттаяла, я снова живу","translation":"我的春天终于来了，我的灵魂融化了，我重新活了过来。","play":"《安娜·卡列尼娜》","song":"（歌名未详）"},
  {"lang":"俄语","original":"Сожжён последний мост\nОтныне мы свободны, и назад пути нет","translation":"最后的桥梁已烧毁，从此刻起我们自由了，再无退路。","play":"《安娜·卡列尼娜》","song":"（歌名未详）"},
  {"lang":"韩语","original":"빼앗긴 들판에도 봄은 오는가\n그 봄이 나에게도 올까","translation":"被剥夺的原野也会迎来春天吗？那春天也会到我这里吗？","play":"《粉丝来信》","song":"（歌名未详）"},
  {"lang":"韩语","original":"파도가 밀려오듯이, 나비 한 마리도 봄의 향기를 가져오리\n모든 것이 다시 살아나리","translation":"就像浪花翻涌，一只蝴蝶也会带来春天的芬芳——万物都将重生。","play":"《粉丝来信》","song":"（歌名未详）"},
  {"lang":"韩语","original":"우주에 다시 빛이 들고\n어둠이 걷히는 이 순간","translation":"宇宙重现微光，黑暗散去的此刻。","play":"《星际信使》","song":"《重现微光》"},
  {"lang":"韩语","original":"이 순간, 운명의 발걸음은 멈추지 않네\n나는 나의 길을 간다","translation":"就在这瞬间，命运的脚步从未停歇，我走我自己的路。","play":"《变身怪医》韩版","song":"《就在这瞬间》"}
]
